language: python

python:
  - "3.5"

env:
  - QT_API=pyqt5

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  # install libegl1-mesa package for the missing libEGL shared object that prevents qt from starting
  - sudo apt-get update
  - sudo apt-get --yes --force-yes install libegl1-mesa
  # make sure pip is up to date so that it can install wheels
  - pip install pip --upgrade
  - pip install -e .
  - pip install -r requirements-dev.txt

script:
  - py.test --cov pyqode

after_success:
  - coveralls
